# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customer_edit_form(object):
    def setupUi(self, customer_edit_form):
        customer_edit_form.setObjectName("customer_edit_form")
        customer_edit_form.resize(450, 400)
        customer_edit_form.setMinimumSize(QtCore.QSize(450, 400))
        customer_edit_form.setMaximumSize(QtCore.QSize(450, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Barbershop/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        customer_edit_form.setWindowIcon(icon)
        customer_edit_form.setStyleSheet("QPushButton{\n"
"    padding: 10 0 10 0;\n"
"    border-radius: 20;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(31, 76, 124);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(46, 123, 175);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(10, 158, 69);\n"
"}")
        self.groupBox_2 = QtWidgets.QGroupBox(customer_edit_form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 431, 331))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border: 0;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 411, 271))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel {\n"
"    color: rgb(136, 0, 0);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(2, 11, 401, 261))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.ma_kh_edit = QtWidgets.QLineEdit(self.widget)
        self.ma_kh_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.ma_kh_edit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.ma_kh_edit.setFont(font)
        self.ma_kh_edit.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.ma_kh_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.ma_kh_edit.setReadOnly(True)
        self.ma_kh_edit.setObjectName("ma_kh_edit")
        self.gridLayout_2.addWidget(self.ma_kh_edit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.sdt_kh_edit = QtWidgets.QLineEdit(self.widget)
        self.sdt_kh_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.sdt_kh_edit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.sdt_kh_edit.setFont(font)
        self.sdt_kh_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.sdt_kh_edit.setObjectName("sdt_kh_edit")
        self.gridLayout_2.addWidget(self.sdt_kh_edit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.ten_kh_edit = QtWidgets.QLineEdit(self.widget)
        self.ten_kh_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.ten_kh_edit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.ten_kh_edit.setFont(font)
        self.ten_kh_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.ten_kh_edit.setObjectName("ten_kh_edit")
        self.gridLayout_2.addWidget(self.ten_kh_edit, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.so_lan_edit = QtWidgets.QLineEdit(self.widget)
        self.so_lan_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.so_lan_edit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.so_lan_edit.setFont(font)
        self.so_lan_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.so_lan_edit.setObjectName("so_lan_edit")
        self.gridLayout_2.addWidget(self.so_lan_edit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.loai_kh_cbx = QtWidgets.QComboBox(self.widget)
        self.loai_kh_cbx.setMinimumSize(QtCore.QSize(0, 32))
        self.loai_kh_cbx.setObjectName("loai_kh_cbx")
        self.gridLayout_2.addWidget(self.loai_kh_cbx, 4, 1, 1, 1)
        self.luu_kh_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.luu_kh_btn.setGeometry(QtCore.QRect(200, 280, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.luu_kh_btn.setFont(font)
        self.luu_kh_btn.setObjectName("luu_kh_btn")
        self.ket_thuc_kh_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ket_thuc_kh_btn.setGeometry(QtCore.QRect(310, 280, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ket_thuc_kh_btn.setFont(font)
        self.ket_thuc_kh_btn.setObjectName("ket_thuc_kh_btn")
        self.widget_5 = QtWidgets.QWidget(customer_edit_form)
        self.widget_5.setGeometry(QtCore.QRect(10, -20, 431, 531))
        self.widget_5.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 222, 223);\n"
"color: rgb(136, 0, 0);\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_15 = QtWidgets.QLabel(customer_edit_form)
        self.label_15.setGeometry(QtCore.QRect(100, 0, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(136, 0, 0, 70%);\n"
"border-radius: 0px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.widget_5.raise_()
        self.groupBox_2.raise_()
        self.label_15.raise_()

        self.retranslateUi(customer_edit_form)
        QtCore.QMetaObject.connectSlotsByName(customer_edit_form)
        customer_edit_form.setTabOrder(self.sdt_kh_edit, self.ten_kh_edit)
        customer_edit_form.setTabOrder(self.ten_kh_edit, self.loai_kh_cbx)
        customer_edit_form.setTabOrder(self.loai_kh_cbx, self.luu_kh_btn)
        customer_edit_form.setTabOrder(self.luu_kh_btn, self.ket_thuc_kh_btn)

    def retranslateUi(self, customer_edit_form):
        _translate = QtCore.QCoreApplication.translate
        customer_edit_form.setWindowTitle(_translate("customer_edit_form", "Sửa khách hàng"))
        self.label_5.setText(_translate("customer_edit_form", "Mã KH:"))
        self.label_3.setText(_translate("customer_edit_form", "SĐT KH:"))
        self.label_4.setText(_translate("customer_edit_form", "Tên KH:"))
        self.label_7.setText(_translate("customer_edit_form", "Số lần đến:"))
        self.label_6.setText(_translate("customer_edit_form", "Loại KH:"))
        self.luu_kh_btn.setText(_translate("customer_edit_form", "Lưu"))
        self.ket_thuc_kh_btn.setText(_translate("customer_edit_form", "Kết thúc"))
        self.label_15.setText(_translate("customer_edit_form", "SỬA KHÁCH HÀNG"))


