# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup_form(object):
    def setupUi(self, signup_form):
        signup_form.setObjectName("signup_form")
        signup_form.resize(370, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(signup_form.sizePolicy().hasHeightForWidth())
        signup_form.setSizePolicy(sizePolicy)
        signup_form.setMinimumSize(QtCore.QSize(370, 570))
        signup_form.setMaximumSize(QtCore.QSize(370, 570))
        signup_form.setStyleSheet("")
        self.label = QtWidgets.QLabel(signup_form)
        self.label.setGeometry(QtCore.QRect(10, 40, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.signup_btn = QtWidgets.QPushButton(signup_form)
        self.signup_btn.setGeometry(QtCore.QRect(80, 450, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.signup_btn.setFont(font)
        self.signup_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(136, 0, 0);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(249, 186, 187);\n"
"\n"
"}")
        self.signup_btn.setObjectName("signup_btn")
        self.label_2 = QtWidgets.QLabel(signup_form)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 101, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/Barbershop/2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(signup_form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 130, 312, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_id_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_id_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.user_id_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.user_id_edit.setFont(font)
        self.user_id_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_id_edit.setMaxLength(30)
        self.user_id_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_id_edit.setObjectName("user_id_edit")
        self.verticalLayout.addWidget(self.user_id_edit)
        self.user_name_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_name_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.user_name_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.user_name_edit.setFont(font)
        self.user_name_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_name_edit.setMaxLength(30)
        self.user_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name_edit.setObjectName("user_name_edit")
        self.verticalLayout.addWidget(self.user_name_edit)
        self.password_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.password_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_edit.setMaxLength(16)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_edit.setObjectName("password_edit")
        self.verticalLayout.addWidget(self.password_edit)
        self.confirmpw_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirmpw_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.confirmpw_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.confirmpw_edit.setFont(font)
        self.confirmpw_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirmpw_edit.setMaxLength(16)
        self.confirmpw_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpw_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmpw_edit.setObjectName("confirmpw_edit")
        self.verticalLayout.addWidget(self.confirmpw_edit)
        self.role_cbx = QtWidgets.QComboBox(self.layoutWidget)
        self.role_cbx.setMinimumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.role_cbx.setFont(font)
        self.role_cbx.setStyleSheet("QComboBox{\n"
"    padding: 0 0 0 120px;\n"
"}")
        self.role_cbx.setFrame(False)
        self.role_cbx.setObjectName("role_cbx")
        self.verticalLayout.addWidget(self.role_cbx)
        self.widget = QtWidgets.QWidget(signup_form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 371, 571))
        self.widget.setStyleSheet("background-color: rgb(136, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.label.raise_()
        self.signup_btn.raise_()
        self.label_2.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(signup_form)
        QtCore.QMetaObject.connectSlotsByName(signup_form)

    def retranslateUi(self, signup_form):
        _translate = QtCore.QCoreApplication.translate
        signup_form.setWindowTitle(_translate("signup_form", "Tạo tài khoản"))
        self.label.setText(_translate("signup_form", "Tạo tài khoản"))
        self.signup_btn.setText(_translate("signup_form", "ĐĂNG KÝ"))
        self.user_id_edit.setPlaceholderText(_translate("signup_form", "Tên đăng nhập"))
        self.user_name_edit.setPlaceholderText(_translate("signup_form", "Họ và tên"))
        self.password_edit.setPlaceholderText(_translate("signup_form", "Mật khẩu"))
        self.confirmpw_edit.setPlaceholderText(_translate("signup_form", "Xác nhận mật khẩu"))
from Fourmenbarbershop_package.gui import bg_img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup_form = QtWidgets.QDialog()
    ui = Ui_signup_form()
    ui.setupUi(signup_form)
    signup_form.show()
    sys.exit(app.exec_())
